# Project Name
TARGET = oled_and_encoder

# Sources
CPP_SOURCES = oled_and_encoder.cpp

# Library Locations
LIBDAISY_DIR = ../extern/libDaisy/
DAISYSP_DIR = ../extern/DaisySP/

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

